version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: hotelbooking_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HotelBookingDb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: src/HotelBooking.API/Dockerfile
    container_name: hotelbooking_api
    depends_on:
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=HotelBookingDb;User=appuser;Password=appuser123;"
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  mysql_data:
